### ISSUE TITLE
geodesic_matlab_api.so is not a     valid shared library

### ISSUE THREAD

**Issue by dvirginz** [zorah/KernelMatching#10]
Should we build it? tried downloading the matlab library  from [here](https://www.mathworks.com/matlabcentral/fileexchange/18168-exact-geodesic-for-triangular-meshes?s_tid=FX_rc2_behav)
but failed.
Do you remember how you built it?
Thanks a lot!

**Comment by zorah** [comment]
Try something like described here with the files from this project (I think I fixed some minor issues from the original matlab code):
https://stackoverflow.com/questions/14884126/build-so-file-from-c-file-using-gcc-command-line
You probably need to link boost. I dont exactly remember what command I used. 

I also made this code for geodesic distance maps that is easier to use (should compile fine with the mex commands given in the cpp files):
https://github.com/zorah/exactgeodesics

**Comment by dvirginz** [comment]
As before, thanks a lot for your responsiveness.
As i'm using a windows machine, I had to build it as a dll and change some files inside the geo repo.

It now works, thanks!

P.S as the SHOT descriptor is compiled for windows, How have you managed to run both the SO and the SHOT mex on the same machine?

**Comment by zorah** [comment]
Cool, let me know if you have other problems!

There is also the shot mexa64 file (for linux) ;) just had the windows file and left it there for convenience
