### ISSUE TITLE
Possible with Octave?

### ISSUE THREAD

**Issue by aalavandhaann** [zorah/KernelMatching#12]
Hi,

Firstly thank you for this contribution. I am researching on a similar idea and was hoping to validate my method with your work by comparing the results. Is it possible that I can run your code on a Linux machine with Octave instead of Matlab? The Linux flavor I use is Ubuntu 18.04 with Octave 4.2.2. I was able to compile the MEX files without any fuss, the only problems I face is for using geodesic CPP. I see you are using CPP shared libraries with Matlab functions libisloaded, unloadlibrary, calllib, etc., which sadly isn't available in Octave. Do you know if there is a workaround for using the geodesics?  Is it possible to use your [exactgeodesics](https://github.com/zorah/exactgeodesics) matlab mex? I was able compile that project sucessfully

Regards,
#0K

**Comment by zorah** [comment]
I have never used Octave so I don't know but the other version of the exact geodesics code is the same only with different ways to call it. It should be usable as well but it is less flexible/slower (basically, at every call you need to build the data structures again) and right now only implemented for exact geodesics but we only use the dijkstra version in the KernelMatching code. 

So option number 1: replace fast_voronoi with your favorite Dijkstra voronoi implementation. Its rather straight forward if runtime is not the main concern.

Option number 2: use the other exact geodesics code (which does not need libload etc) but you will need to replace the GeodesicAlgorithmExact with GeodesicAlgorithmDijkstra in geodesic_exact.cpp. If you have this it should be rather easy to replace in fast_voronoi, drop most of the code and call the new function with the old sets (sources <-> source_points, targets <-> remaining_samples, probably). (No guarantee that it is actually that easy, maybe some fumbling required...)

I hope this helps.

**Comment by aalavandhaann** [comment]
Yes, that is what I am doing right now. In your source code I am trying to find out the scripts that use the Geodesics code, and the methods of Geodesics used. In the other project for Geodesics I saw there are only two routines for geodesic distances, and distance map. Hence, the fumbling started already, ;-). Thanks for pointing out that its only fast_voronoi that needs changes. I will see what best I can do to this. 
Since this code is not an original port for Octave but was intended for Matlab, I repect that decision and would like to close this issue. Many thanks for your prompt and useful reply. 

Regards,
#0K

**Comment by aalavandhaann** [comment]
Hi,

I finally managed to get a license of Matlab from my school and happy to say that your code works just fine. Can you please tell me if there is a way to save the mapping between two meshes as point to surface (vertex->barycentric) as a bijective map? Or atleast a map between source to target? 

Regards,
#0K

**Comment by aalavandhaann** [comment]
Do you think the below is a plausible result (Pair of human ears)? Are there ways to improve the result? 
![Result](https://user-images.githubusercontent.com/8164567/68719991-cc01ae80-057b-11ea-911e-8fa44d64bb83.jpg)

**Comment by zorah** [comment]
About the point to surface map: No, this is not possible (because it is solving only for point-to-point internally so no barycentric possible, you can of course always convert them but it will always land on a vertex). The final solution should be close to a bijection but there is no guarantee that all points are matched. If this is important and your shape is not too large, you can turn off the multi-scale pipeline by setting options.problemSizeInit to the number of vertices. This will solve a LAP with the number of vertices which might be infeasible (depends on your computer how large but maybe around 5k if you are willing to wait long enough).

Your result: This looks very wrong. I would assume the time parameters (tX, tY) do not fit for your surface area. Did you comment in line 70-73 which will scale the shapes to have roughly the right area?

**Comment by aalavandhaann** [comment]
Firstly, many many thanks for your time. I am hoping to get your method to work for the dataset I have chosen. It will help me in testing your approach as a comparison to ours and for evaluation. Most of the approaches demand near-isometry, and genus-restrictions imposed. Your method, on the other hand, is devoid of such limitations, which makes it easier for me to argue. Secondly, I am sincerely sorry for this delayed reply. I wanted to get all the data in place so I can present a clear objective to you that can save you precious time. 

Finally, as you mentioned I have changed the HKS tx and ty values based on testing in my own (Blender) implementation. The values for both are good with logspace between ```logspace(log(0.00001), log(1.0), opts.maxIter(value of 10 is used))``` instead of log base 10 values, which you have used. I have attached a picture below to show how similar the meshes are with the selected HKS. 
![Selection_195](https://user-images.githubusercontent.com/8164567/69190001-85690280-0aed-11ea-9d40-2759e9dbd62b.png)

Now with the above HKS values and uncommenting the line 73
```refarea = 1.93e+04;``` gives me the result like this, 

![Ears](https://user-images.githubusercontent.com/8164567/69192152-04f8d080-0af2-11ea-8add-ea93ff6aba9d.png)

Oh, btw the meshes are unitized in size. Both are aligned and unitized before running any algorithm.

Regards,

#0K

**Comment by zorah** [comment]
Okay, that is still a weird result. Is it correct that one of the shapes a much higher number of vertices?

First, you should *not* change the time values and comment in the refarea. The time values were tuned to go with this exact area, so if you have good time values for your shape you should not rescale them.

Second, since your target mesh is so noisy the SHOT descriptors will be useless (and give a really bad initialization). If they are aligned already, you could try to replace the shot descriptors with the vertex coordinates instead (we do not use this because we consider large non-rigid deformations but for your case it might be good enough). 

Feel free to let me know if it still not works. Your project looks really interesting :)

**Comment by aalavandhaann** [comment]
> Okay, that is still a weird result. Is it correct that one of the shapes a much higher number of vertices?
- hmmmm. Yes one of them is a very high resolution scan of real human ear with 110k vertices and the other one is a template with 20K vertices. 

> First, you should not change the time values and comment in the refarea. The time values were tuned to go with this exact area, so if you have good time values for your shape you should not rescale them.
- yes, I tried this too. I did not use refarea and commented it out. Just kept these good timescale values and the results were still the same. Is that what you meant?

> Second, since your target mesh is so noisy the SHOT descriptors will be useless (and give a really bad initialization). If they are aligned already, you could try to replace the shot descriptors with the vertex coordinates instead (we do not use this because we consider large non-rigid deformations but for your case it might be good enough).
- okay that's a good direction of investigation. I will try and change the SHOT descriptors to vertex coordinates. But if I remember well SHOT descriptors use FLANN right? Don't they already use nearest vertex or surface coordinate? Sorry if that was a stupid question. 
>Feel free to let me know if it still not works. Your project looks really interesting :)
- I am really thankful to your support and timely advice. If things go well then perhaps I should acknowledge your name as well for the support. But I really appreciate your efforts to help a fellow researcher (PhD student)

**Comment by zorah** [comment]
>     * hmmmm. Yes one of them is a very high resolution scan of real human ear with 110k vertices and the other one is a template with 20K vertices.
So the difference in resolution and vertex density is definitely not the perfect setup, it will probably never be really accurate ( good for you if you just want to show yours is better ;) ) 

>     * yes, I tried this too. I did not use refarea and commented it out. Just kept these good timescale values and the results were still the same. Is that what you meant?
Yes, that was what I meant.

> > Second, since your target mesh is so noisy the SHOT descriptors will be useless (and give a really bad initialization). If they are aligned already, you could try to replace the shot descriptors with the vertex coordinates instead (we do not use this because we consider large non-rigid deformations but for your case it might be good enough).

>     * okay that's a good direction of investigation. I will try and change the SHOT descriptors to vertex coordinates. But if I remember well SHOT descriptors use FLANN right? Don't they already use nearest vertex or surface coordinate? Sorry if that was a stupid question.
It does use FLANN but then it is based on the normals and not the vertex coordinates (which is a lot more sensitive to noise but robust against rigid transformations)

So I think the different resolution is a problem in this case (the algorithm was not so much made for template matching... in the sense that if there are not enough vertices to match, the matches tend to stick together instead of covering all areas equally) and although I hope you should be able to get better results than what you have right now, I am not sure if they will be good enough for showing a nice comparison. (I dont want you to spend too much time on this for nothing) 
If you would be willing to send one of your pairs to me, I can try out some things and let you know if I think its feasible at all

**Comment by aalavandhaann** [comment]
Dear Zorah,

I sincerely thank you for all the guidance and your attempt to try on pair of meshes. Here they are, 
[Meshes.zip](https://github.com/zorah/KernelMatching/files/3888100/Meshes.zip). I have attached both the highres and the low res versions for both. The template is 20k and the scan is 100k and they are in OFF format. Kindly let me know if this pair works. Once again many thanks for helping me out. 

Regards,
#0K

**Comment by aalavandhaann** [comment]
Hi Zorah,

Sorry to bother you but was it possible for you to run test on the pair of meshes? Did you have any luck. 

Regards,
#0K

**Comment by zorah** [comment]
Sorry, I am having problems with this size of meshes on my laptop. I will be back in the university in January and try it then.

**Comment by aalavandhaann** [comment]
Thank you very much and I understand. Kindly let me know during January if you can.

Regards,

#0K

**Comment by zorah** [comment]
Okay, so I got this solution when using only one iteration and 3k vertices, its sparse but looks very good to me:
![3000only](https://user-images.githubusercontent.com/9741133/72170764-bec53c80-33d1-11ea-9e89-01acbbffd13f.png)

used this code for setup (you could get a denser matching by increasing opts.problemSizeInit but this gets slow/needs a lot RAM, depends on your computer how high you can go):

refarea = 1.93e+04; % time parameters are adjusted to a certain surface area
                    % this is used to rescale the input shapes
X.VERT = X.VERT ./ sqrt(sum(calc_tri_areas(X))) .* sqrt(refarea);
Y.VERT = Y.VERT ./ sqrt(sum(calc_tri_areas(Y))) .* sqrt(refarea);


X.area = sum(calc_tri_areas(X));
Y.area = sum(calc_tri_areas(Y));

%% options
opts = struct;
opts.shot_num_bins = 10; % number of bins for shot
opts.shot_radius = 5; % percentage of the diameter used for shot

opts.lambda = 1e7; % lambda weighting the regularizer
opts.mu = 1; % mu weighting the data term after the first iteration
opts.maxIter = 10; % max iterations in each filter step
opts.k = 3; % factor increasing the sampling in each multi scale iteration
opts.problemSize = 1000; % max LAP size solved
opts.problemSizeInit = 3000; % max LAP size for first iteration (this might 
                             % be bigger than problemSize, if too low bad 
                             % results will propagate too much through the multi scale, but too big will be slow)
opts.use_par = false; % whether to use parfor while working on each scale of the problem.                             
opts.tX = logspace(log10(500),log10(10),opts.maxIter); % time parameter for the heat kernels on X
opts.tY = logspace(log10(500),log10(10),opts.maxIter); % time parameter for the heat kernels on Y
opts.t_it = @(t, k, i) (t(i) ./ 1);
% opts.tX = logspace(log10(500),log10(50),opts.maxIter); % time parameter for the heat kernels on X

opts.partial = false; % allows entire parts of the shape to be not matched, based on difference of area
opts.vis = false; % shows (or not) the result of each multiscale iteration
opts.n_evecs = 500; % number of eigenfunctions computed
opts.oneIteration = true;

opts.convexify = false;
opts.rho = 0.5;

opts.filter = 'hk';


I started the same setup but with opts.oneIteration  = false which should give a dense matching but its still running, will let you know on Monday what happend!

**Comment by aalavandhaann** [comment]
Amazing results. I completely agree that the sparse map is really good. I am going run the code on my end where it will save the correspondences map. Then I want to deform and see how the sparse map is helpful.  Thank you a ton. I am almost reaching the deadline of submission but I am hopeful this can be used. 

Regards,
#0K

**Comment by aalavandhaann** [comment]
The result is quite good even from the sparse correspondence I would say. Using the sparse registration I solved for a laplacian minimization using the sparse registration as constraints and the results are quite cool. 

![Selection_094](https://user-images.githubusercontent.com/8164567/72204032-98d78080-3441-11ea-8b23-1a3c8bcbced4.png)

Thank you very much for this.

Regards,
#0K

**Comment by zorah** [comment]
Nice! I am glad it works. Good luck with your submission!

**Comment by aalavandhaann** [comment]
Many thanks for all the help. Can you tell me how `refarea = 1.93e+04;` is selected? 

Regards,
#0K

**Comment by zorah** [comment]
This is the area of all shapes in the tosca dataset (approximately). So we parameter tuned the heat diffusion on tosca but did not find a good formula to make the heat times depend on the area robustly... so we just rescale all shapes to this area. (its hacky... but it works)
