### ISSUE TITLE
Could you give your data of kids  you uesd in this experiment?

### ISSUE THREAD

**Issue by shtanf** [zorah/KernelMatching#6]
Hello ,I am very sorry to bither you again and again.I think my data is suitabe for your first experiment about kids,but I do not konw how you deal with your data of kids and how it runs,especially do not find the input codes of the sparse collection of point-wise matches(as few as two).So could you give me the data of the kids you uesd in this experiment and the related implementation codes just on the kids.And if it is nessary to normalize the data before use it? My email is 674834458@qq.com. I will be forever grateful to you for extending my any help.

**Comment by zorah** [comment]
We did not use any sparse inputs on the kids, only SHOT descriptors, you can find the entire data set here:
https://vision.in.tum.de/data/datasets/topkids

What do you mean by normalization? We normalize the area (its part of the sample code) but nothing else
