### ISSUE TITLE
remove outliers

### ISSUE THREAD

**Issue by lixiang-ucas** [zorah/KernelMatching#7]
Hi Zorah, can you give a brief introduction of how to use your code to run PMF in order to remove the outliers of my correspondence results? Thanks.

**Comment by zorah** [comment]
Hi,
this is not an implementation of the PMF paper (although the two are related) and correspondence denoising is not a part of it. In theory you can replace (or concatinate) the SHOT descriptors in run_example with landmark descriptors of your noisy correspondence (for example a unit vector for each correspondence) but I have never tried this and I am not sure how well it will work for denoising.
