### ISSUE TITLE
remesh_and_fix algorithm

### ISSUE THREAD

**Issue by dvirginz** [zorah/KernelMatching#8]
Hi, 
In the example_run script you mention remesh_and_fix, which is indeed needed in some meshes:)

Can you please provide the script?
Thanks:)

**Comment by zorah** [comment]
Hi, 
it uses qslim and MeshFix, you can find them here:
https://www.cs.cmu.edu/~./garland/quadrics/qslim.html
https://github.com/MarcoAttene/MeshFix-V2.1
