### ISSUE TITLE
What() is:invalid vector<T> subscript

### ISSUE THREAD

**Issue by dvirginz** [zorah/KernelMatching#9]
I'm having the following error running the PMF example

Unexpected Standard exception from MEX file.What() is:invalid vector<T> subscript..Error in example_run (line 154)X.desc = calc_shot(X.VERT',X.TRIV', 1:X.n, opts.shot_num_bins, opts.shot_radius*sqrt(X.area)/100, 3)';

with a mesh processed by the fixme algorithm (attached both the lores and the regular mesh)

Do you know what can be the problem?

Thanks a lot:)

[Uploading lores_reg_mesh_fixed.zip…]()

**Comment by robertod** [comment]
For reference, this error occurs when the input X.TRIV is of an integer type. To fix this, modify your code to convert this to a floating point type, i.e.:
`X.desc = calc_shot(X.VERT',double(X.TRIV)', 1:X.n, opts.shot_num_bins, opts.shot_radius*sqrt(X.area)/100, 3)';`
